enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  fyko:
    npmAlwaysAuth: true
    npmAuthToken: ${NODE_AUTH_TOKEN}
    npmRegistryServer: 'https://registry.npmjs.com'

yarnPath: .yarn/releases/yarn-3.2.0-rc.16.cjs
