enableGlobalCache: true

nodeLinker: node-modules

npmScopes:
  fyko:
    npmAlwaysAuth: false
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.com"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
